# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Only show directory, git branch, and prompt character
format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
